name: CI/CD Java Spring Boot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # baixar código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # instalar Java (sem Docker)
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # cache do Maven (opcional, acelera builds)
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # rodar os testes (CI)
      - name: Run tests
        run: mvn -B test

      # empacotar aplicação (gera .jar)
      - name: Build JAR
        run: mvn -B package -DskipTests=false

      # publicar o .jar como artefato do pipeline (CD)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
